/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as LiveNavigationRouteImport } from './routes/live-navigation'
import { Route as SensorFusionRouteImport } from './routes/sensor-fusion'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulationLabRouteImport } from './routes/simulation-lab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveNavigationRoute = LiveNavigationRouteImport.update({
  id: '/live-navigation',
  path: '/live-navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorFusionRoute = SensorFusionRouteImport.update({
  id: '/sensor-fusion',
  path: '/sensor-fusion',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationLabRoute = SimulationLabRouteImport.update({
  id: '/simulation-lab',
  path: '/simulation-lab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/live-navigation': typeof LiveNavigationRoute
  '/sensor-fusion': typeof SensorFusionRoute
  '/settings': typeof SettingsRoute
  '/simulation-lab': typeof SimulationLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/live-navigation': typeof LiveNavigationRoute
  '/sensor-fusion': typeof SensorFusionRoute
  '/settings': typeof SettingsRoute
  '/simulation-lab': typeof SimulationLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/live-navigation': typeof LiveNavigationRoute
  '/sensor-fusion': typeof SensorFusionRoute
  '/settings': typeof SettingsRoute
  '/simulation-lab': typeof SimulationLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/live-navigation'
    | '/sensor-fusion'
    | '/settings'
    | '/simulation-lab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/live-navigation'
    | '/sensor-fusion'
    | '/settings'
    | '/simulation-lab'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/live-navigation'
    | '/sensor-fusion'
    | '/settings'
    | '/simulation-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LiveNavigationRoute: typeof LiveNavigationRoute
  SensorFusionRoute: typeof SensorFusionRoute
  SettingsRoute: typeof SettingsRoute
  SimulationLabRoute: typeof SimulationLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-navigation': {
      id: '/live-navigation'
      path: '/live-navigation'
      fullPath: '/live-navigation'
      preLoaderRoute: typeof LiveNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensor-fusion': {
      id: '/sensor-fusion'
      path: '/sensor-fusion'
      fullPath: '/sensor-fusion'
      preLoaderRoute: typeof SensorFusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation-lab': {
      id: '/simulation-lab'
      path: '/simulation-lab'
      fullPath: '/simulation-lab'
      preLoaderRoute: typeof SimulationLabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LiveNavigationRoute: LiveNavigationRoute,
  SensorFusionRoute: SensorFusionRoute,
  SettingsRoute: SettingsRoute,
  SimulationLabRoute: SimulationLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
